encrypt:
	ansible-vault encrypt group_vars/all/vault.yml

decrypt:
	ansible-vault decrypt group_vars/all/vault.yml

bind:
	ansible-playbook bind.yml -i inventory -vv

rsnapshot:
	ansible-playbook rsnapshot.yml -i inventory -vv

samba:
	ansible-playbook samba.yml -i inventory -vv
