10_0_2_2_mnt: /mnt/10.0.2.2
10_0_2_2_opt: DESCTOP support eeprom 1.0

10_0_2_5_mnt: /mnt/10.0.2.5
10_0_2_5_opt: DESCTOP support eeprom 1.0

sangig06_mnt: /mnt/sangig06
sangig06_opt: Desctop support eeprom 2.1
