A_MNT: /mnt/10.0.3.2
A_OPT: DESKTOP support eeprom 1.0
A_PID: 2

B_MNT: /mnt/10.0.3.5/obmen
B_OPT: OBMEN support eeprom 1.0
B_PID: 51

C_MNT: /mnt/10.0.3.5/my_doc
C_OPT: MY_DOC support eeprom 1.0
C_PID: 52

D_MNT: /mnt/10.0.3.5/mail_new_2018
D_OPT: MAIL_NEW_2018 support eeprom 1.0
D_PID: 53

hosts_list:
  - 10.0.3.2
  - 10.0.3.5/obmen
  - 10.0.3.5/my_doc
  - 10.0.3.5/mail_new_2018

dirs_list:
  - rsnapshot_10.0.3.5

pathToBackupDir: /var/ooi_backup/
